### ISSUE TITLE
Compatibility with newer numpy and scvi-tools?

### ISSUE THREAD

**Issue by rekado** [ohlerlab/liam#1]
I'd like to package this for GNU Guix.  We've got more recent versions of numpy (1.23.x) and scvi-tools (1.0.4) than those versions mentioned in pyproject.toml.  Is liam known to be incompatible with more recent versions of these packages?  If so, would it be of interest to make changes to support these more recent versions?

**Comment by prauten** [comment]
Hi there. Thanks for your interest in liam. Concerning the package version compatibility - after reading the release notes of numpy, I don't expect major issues with numpy version 1.23.x and could test it if of interest. Concerning scvi-tools, however, many breaking changes have been introduced between version 0.14.3 (liam dependency) and version 1.0.4. Of course, we would love you to package liam for guix.  Unfortunately, we are currently unable to support the required updates concerning scvi-tools. Let me know if I could check for/enable the numpy compatibility.

**Comment by rekado** [comment]
I'm afraid the dependency on scvi-tools 0.14.3 is going to be a practical obstacle.  That release is around 3 years old and has restrictions on what packages it is compatible with.  This includes old versions of numpy, pytorch (version 1 instead of 2), pytorch-lightning (same), pandas (version 1 vs 2), etc.

I'm afraid it could be rather challenging to build old versions of all these packages for an unmaintained version of scvi-tools.

**Comment by prauten** [comment]
At the moment I cannot support the required updates, but will inform you if I have the opportunity to do so.
